hl.workspace_rule({workspace = 1, default = true, persistent = true, monitor = "eDP-1"})
hl.workspace_rule({workspace = 2, default = false, persistent = false, monitor = "eDP-1"})
hl.workspace_rule({workspace = 3, default = true, persistent = true, monitor = "HDMI-A-1"})
hl.workspace_rule({workspace = 4, default = false, persistent = false, monitor = "HDMI-A-1"})
hl.workspace_rule({workspace = 7, default = false, persistent = true, monitor = "eDP-1"})
hl.workspace_rule({workspace = 8, default = false, persistent = true, monitor = "eDP-1"})
hl.workspace_rule({workspace = 9, default = false, persistent = true, monitor = "eDP-1"})
